/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeFieldset: typeof import('primevue/fieldset')['default']
    PrimeInputGroup: typeof import('primevue/inputgroup')['default']
    PrimeInputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimePaginator: typeof import('primevue/paginator')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimePopover: typeof import('primevue/popover')['default']
    PrimeProgressSpinner: typeof import('primevue/progressspinner')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeStep: typeof import('primevue/step')['default']
    PrimeStepItem: typeof import('primevue/stepitem')['default']
    PrimeStepPanel: typeof import('primevue/steppanel')['default']
    PrimeStepper: typeof import('primevue/stepper')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
